name: Code_Style_Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install clang-format
      run: sudo apt-get install -y clang-format
    
    - name: Run clang-format
      run: |
        find . -name '*.cpp' -o -name '*.h' | xargs clang-format -style=file -i
        git diff --exit-code